### ISSUE TITLE
ReleaseDate mit DateTimePicker

### ISSUE THREAD

**Issue by Holzkohlen** [Holzkohlen/projectmeymey#14]
Muss fancy!

**Comment by DTheRealK** [comment]
[Festlegen und Zurückgeben von Datumsangaben](https://msdn.microsoft.com/de-de/library/aa983724(v=vs.71).aspx)
[Anzeigen der Zeit mithilfe des DateTimePicker](https://msdn.microsoft.com/de-de/library/ms229631(v=vs.110).aspx)

**Comment by Holzkohlen** [comment]
DateTime dtIrgendwas = DateTime.Parse(sJahr, sMonat, sTag);

**Comment by DTheRealK** [comment]
[DateTime dt = DateTime.Parse("6/22/2009 07:00:00 AM");
](http://stackoverflow.com/questions/1026841/how-to-get-only-time-from-date-time-c-sharp)

**Comment by Holzkohlen** [comment]
ToString("MMMM dd, yyyy")

**Comment by Holzkohlen** [comment]
Super dumm. Ausleihdatum ist immer aktuelles Datum!
Umbenannt in ReleaseDate mit Datepicker!
