### ISSUE TITLE
Fancy Icon

### ISSUE THREAD

**Issue by Holzkohlen** [Holzkohlen/projectmeymey#2]
Selbsterklärend

**Comment by DTheRealK** [comment]
![1495293326_bt_binder](https://cloud.githubusercontent.com/assets/28632423/26274941/141c5f44-3d56-11e7-9c73-557eb759df50.png) <BR>[Ordner](https://www.iconfinder.com/icons/905575/binder_data_document_documents_files_icon#size=128)<BR>

**Comment by DTheRealK** [comment]
![1495293404_file_storage](https://cloud.githubusercontent.com/assets/28632423/26274969/9701fd10-3d56-11e7-9247-c699d504401c.png)<BR> [Der Ordner](https://www.iconfinder.com/icons/1214625/data_document_extension_file_format_sheet_storage_icon#size=128)

**Comment by DTheRealK** [comment]
![group-icon](https://cloud.githubusercontent.com/assets/28632423/26275026/b7463662-3d57-11e7-937c-3694d7eb6028.png)<BR> [Ordner mit Personen](http://www.iconarchive.com/show/zero-folders-icons-by-arkangl300/group-icon.html)

**Comment by Holzkohlen** [comment]
Wieso Ordner?

Ich dachte an was in der Richtung. 
https://pixabay.com/de/b%C3%BCcher-icon-buchsymbol-symbol-satz-1673578/
http://www.freepik.com/free-vector/colored-books-pack_812031.htm

**Comment by Holzkohlen** [comment]
Geil wär auch sowas:
https://www.123rf.com/photo_42854152_stock-vector-flat-books-with-bookmarks-circle-icon-with-long-shadow-back-to-school-and-education-wisdom-knowledge.html
Nur halt mit unterschiedlichen Medien, statt nur Büchern
