### ISSUE TITLE
Ein gutes Programm machen

### ISSUE THREAD

**Issue by dedChar** [Holzkohlen/projectmeymey#3]
Sollte selbsterklärend sein

**Comment by Holzkohlen** [comment]
Ich will alles schön organizen und dann kommt deine "issue". 
Hab viel zu hart gelacht 👯‍♂️ 👍

**Comment by dedChar** [comment]
woah wie habt ihr das denn geschafft

**Comment by Holzkohlen** [comment]
Ach weißt du, "gut" ist so ein dehnbarer Begriff. Aber wir sind noch nicht fertig. Ich räum bloß bissl bei Github auf^^
